/**
 * Bundle the icons this site actually uses.
 *
 * `@iconify/svelte` fetches icon data from `api.iconify.design` at runtime
 * unless it is given the data directly. That means a third-party request per
 * visitor, no icons at all before hydration or without JavaScript, and a site
 * that loses its icons if that host is unreachable. None of that is acceptable
 * on a site that gates analytics behind a consent banner.
 *
 * So: scan the source for `tabler:*` names, pull just those from the installed
 * icon set, and write them out as a module the app imports. Roughly two dozen
 * icons out of the set's six thousand.
 *
 * Run `pnpm icons` after adding or removing an icon. `icons.spec.ts` fails the
 * build if the generated file and the source ever disagree, so forgetting is
 * caught rather than silently falling back to the network.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const SRC = 'src';
const OUT = 'src/lib/icons.generated.ts';

/**
 * Every `tabler:name` mentioned anywhere in the source.
 * @param {string} dir
 * @returns {string[]}
 */
export function collectNames(dir = SRC) {
	/** @type {Set<string>} */
	const names = new Set();
	/** @param {string} path */
	const walk = (path) => {
		for (const entry of readdirSync(path)) {
			const full = join(path, entry);
			if (statSync(full).isDirectory()) {
				walk(full);
				// Tests are not shipped and may name icons that do not exist, so they
				// are not evidence that the site uses one.
			} else if (
				/\.(svelte|ts|js)$/.test(entry) &&
				!/\.(spec|test)\.[tj]s$/.test(entry) &&
				!full.endsWith('icons.generated.ts')
			) {
				for (const [, name] of readFileSync(full, 'utf8').matchAll(/tabler:([a-z0-9-]+)/g)) {
					names.add(name);
				}
			}
		}
	};
	walk(dir);
	return [...names].sort();
}

/* Everything below runs only when invoked directly, so the scanner above can
 * be imported by a test without regenerating anything. */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	const set = require('@iconify-json/tabler/icons.json');
	const { width, height } = set;
	// The JSON's inferred type is a literal union of all 6,232 names, which
	// cannot be indexed by an arbitrary string — widen it once, here.
	/** @type {Record<string, { body: string }>} */
	const icons = set.icons;
	const names = collectNames();

	const missing = names.filter((n) => !(n in icons));
	if (missing.length) {
		console.error(`Unknown tabler icons: ${missing.join(', ')}`);
		process.exit(1);
	}

	const body = names
		.map((name) => `\t'tabler:${name}': ${JSON.stringify(icons[name])}`)
		.join(',\n');

	writeFileSync(
		OUT,
		`// Generated by scripts/build-icons.mjs — do not edit.
	// Run \`pnpm icons\` to regenerate after changing which icons the site uses.
	import type { IconifyIcon } from '@iconify/types';

	const DEFAULTS = { width: ${width}, height: ${height} };

	/** The ${names.length} icons this site uses, inlined so nothing is fetched at runtime. */
	export const ICONS: Record<string, IconifyIcon> = {
	${body}
	};

	/** Icon data by \`tabler:name\`, or undefined if it was never bundled. */
	export function iconData(name: string): IconifyIcon | undefined {
		const icon = ICONS[name];
		return icon && { ...DEFAULTS, ...icon };
	}
	`
	);

	console.log(`Bundled ${names.length} icons → ${relative(process.cwd(), OUT)}`);
}
